metadata.format.version = "1.1"

[versions]
velocity = "3.4.0-SNAPSHOT"
blossom = "2.1.0"
shadow = "9.1.0"
runvelocity = "3.0.0"
jdwebhooks = "1.1.0"
log4j2 = "2.25.1"

[libraries]
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
jdwebhooks = { module = "io.github.4drian3d:jdwebhooks", version.ref = "jdwebhooks" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2" }

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
